### ISSUE TITLE
pip install clang: error: unknown argument: ‘-fstack-protector-strong’

### ISSUE THREAD

**Issue by Piknik1990** [getsentry/libsourcemap#14]
Hello!

Every time I install Sentry, I run into a new problem.

Now I need install Sentry service on the Centos 7.4 OS.

I run next commands:

\# yum -y update
\# reboot
\# yum -y install python python2-pip python-virtualenv postgresql redis python python2-pip python-virtualenv postgresql gcc gcc-c++ libjpeg-turbo libffi libxml2 libxslt libyaml libjpeg-turbo-devel zlib-devel postgresql-devel libffi-devel numpy python34-numpy clang libyaml-devel
\# systemctl start redis
\# systemctl enable redis

\# pip install --upgrade pip
\# pip install redis==2.10.5

\# mkdir -p /sentry/sentry-venv
\# virtualenv /sentry/sentry-venv/
\# source /sentry/sentry-venv/bin/activate
\# pip install -U sentry

And I get next errors:
...
`

    Downloading/unpacking libsourcemap>=0.8.2,<0.9.0 (from sentry)
    Downloading libsourcemap-0.8.2.zip (765kB): 765kB downloaded
    Saved ./sentry-inst/libsourcemap-0.8.2.zip
    Running setuppy egg_info for package libsourcemap
    clang: error: unknown argument: '-fstack-protector-strong’
    clang: error: unknown argument: '-fstack-protector-strong’
    clang: error: unknown argument: '-fstack-protector-strong’
    clang: error: unknown argument: ‘-fstack-protector-strong’

    No working compiler found, or bogus compiler options passed to
    the compiler from Python’s standard “distutils” module. See
    the error messages above. Likely, the problem is not related
    to CFFI but generic to the setuppy of any Python package that
    tries to compile C code. (Hints: on OS/X 10.8, for errors about
    -mno-fused-madd see
    Otherwise, see or
    the IRC channel #python on ircfreenodenet.)
    Traceback (most recent call last):
    File “”, line 16, in
    File “/sentry/sentry-venv/build/libsourcemap/setup.py”, line 117, in
    'Topic :: Software Development :: Libraries :: Python Modules’
    File “/usr/lib64/python2.7/distutils/core.py”, line 112, in setup
    _setup_distribution = dist = klass(attrs)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/dist.py”, line 265, in init
    self.fetch_build_eggs(attrs.pop(‘setup_requires’))
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/dist.py”, line 289, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
    File “/sentry/sentry-venv/lib/python2.7/site-packages/pkg_resources.py”, line 618, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/pkg_resources.py”, line 862, in best_match
    return self.obtain(req, installer) # try and download/install
    File “/sentry/sentry-venv/lib/python2.7/site-packages/pkg_resources.py”, line 874, in obtain
    return installer(requirement)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/dist.py”, line 339, in fetch_build_egg
    return cmd.easy_install(req)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/command/easy_install.py”, line 623, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/command/easy_install.py”, line 653, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/command/easy_install.py”, line 849, in install_eggs
    return self.build_and_install(setup_script, setup_base)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/command/easy_install.py”, line 1130, in build_and_install
    self.run_setup(setup_script, setup_base, args)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/command/easy_install.py”, line 1118, in run_setup
    raise DistutilsError(“Setup script exited with %s” % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with 1
    Complete output from command python setuppy egg_info:
    clang: error: unknown argument: ‘-fstack-protector-strong’

    clang: error: unknown argument: ‘-fstack-protector-strong’

    clang: error: unknown argument: ‘-fstack-protector-strong’

    clang: error: unknown argument: ‘-fstack-protector-strong’

    No working compiler found, or bogus compiler options passed to
    the compiler from Python’s standard “distutils” module. See
    the error messages above. Likely, the problem is not related
    to CFFI but generic to the setuppy of any Python package that
    tries to compile C code. (Hints: on OS/X 10.8, for errors about
    -mno-fused-madd see
    Otherwise, see or
    the IRC channel #python on ircfreenodenet.)
    Traceback (most recent call last):
    File “”, line 16, in
    File “/sentry/sentry-venv/build/libsourcemap/setup.py”, line 117, in
    ‘Topic :: Software Development :: Libraries :: Python Modules’
    File “/usr/lib64/python2.7/distutils/core.py”, line 112, in setup
    _setup_distribution = dist = klass(attrs)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/dist.py”, line 265, in init
    self.fetch_build_eggs(attrs.pop(‘setup_requires’))
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/dist.py”, line 289, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
    File “/sentry/sentry-venv/lib/python2.7/site-packages/pkg_resources.py”, line 618, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/pkg_resources.py”, line 862, in best_match
    return self.obtain(req, installer) # try and download/install
    File “/sentry/sentry-venv/lib/python2.7/site-packages/pkg_resources.py”, line 874, in obtain
    return installer(requirement)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/dist.py”, line 339, in fetch_build_egg
    return cmd.easy_install(req)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/command/easy_install.py”, line 623, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/command/easy_install.py”, line 653, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/command/easy_install.py”, line 849, in install_eggs
    return self.build_and_install(setup_script, setup_base)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/command/easy_install.py”, line 1130, in build_and_install
    self.run_setup(setup_script, setup_base, args)
    File “/sentry/sentry-venv/lib/python2.7/site-packages/setuptools/command/easy_install.py”, line 1118, in run_setup
    raise DistutilsError(“Setup script exited with %s” % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with 1
    Cleaning up…
    Command python setuppy egg_info failed with error code 1 in /sentry/sentry-venv/build/libsourcemap
`

Exactly the same problem was 2 months ago. I thought you would fix it, but the description of this problem did not appear even in Google.

Developers clang disable option -fstack-protector-strong and what I can now for install Sentry - I no idea.

How I can fix this problem now and continue install?

**Comment by mattrobenolt** [comment]
The problem here is you’re not getting a wheel for libsourcemap. This means you’re running on some architecture that we’re not building a binary distribution for. Otherwise, you need a Rust compiler to compile from source. 

It’s also worth noting that we don’t support running Sentry on CentOS.

**Comment by mitsuhiko** [comment]
This can also happen on ancient pip versions which given you are on centos is not unlikely.

**Comment by Piknik1990** [comment]
I have PIP and CentOS of the last versions. This is very strangely, what libsourcemap do not support popularly tuned OS.

If I try install libsourcemap from source - I get follow:

```
\# yum -y install python python2-pip python-virtualenv postgresql redis python python2-pip python-virtualenv postgresql gcc gcc-c++ libjpeg-turbo libffi libxml2 libxslt libyaml libjpeg-turbo-devel  zlib-devel postgresql-devel libffi-devel numpy python34-numpy clang libyaml-devel git
\# systemctl start redis
\# systemctl enable redis


\# mkdir  $HOME/libsourcemap
\# git clone https://github.com/getsentry/libsourcemap.git $HOME/libsourcemap
\# cd $HOME/libsourcemap
\# make

`
pip install --verbose --editable .
Obtaining file:///root/libsourcemap
  Running setup.py (path:/root/libsourcemap/setup.py) egg_info for package from file:///root/libsourcemap
    Running command python setup.py egg_info
    clang: error: unknown argument: '-fstack-protector-strong'
    clang: error: unknown argument: '-fstack-protector-strong'
    clang: error: unknown argument: '-fstack-protector-strong'
    clang: error: unknown argument: '-fstack-protector-strong'

       No working compiler found, or bogus compiler options passed to
       the compiler from Python's standard "distutils" module.  See
       the error messages above.  Likely, the problem is not related
       to CFFI but generic to the setup.py of any Python package that
       tries to compile C code.  (Hints: on OS/X 10.8, for errors about
       -mno-fused-madd see http://stackoverflow.com/questions/22313407/
       Otherwise, see https://wiki.python.org/moin/CompLangPython or
       the IRC channel #python on irc.freenode.net.)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/libsourcemap/setup.py", line 117, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules'
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with 1
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /root/libsourcemap/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 518, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /root/libsourcemap/
make: *** [develop] Ошибка 1
```

Same mistake. 

In the repository Centos 7 is contained clang 3.4.2, but option fstack-protector-strong add on the 3.8 version.

Now I try update clang from source

**Comment by mattrobenolt** [comment]
As mentioned, you are also going to need a Rust compiler since this is written in Rust.

**Comment by mitsuhiko** [comment]
What happens if you download the wheel and pip install it? Because installing from source is unlikely going to result in an enjoyable experience since we compile a chunk of llvm in this library.

**Comment by Piknik1990** [comment]
What is a "wheel"?

**Comment by mitsuhiko** [comment]
One of the files here: https://pypi.python.org/pypi/libsourcemap

Download the one for your linux and then try to pip install it manually. It most likely gives you an error that tells you why it thinks it does not match.

**Comment by Piknik1990** [comment]
I install Sentry.

I do not installed whl-file libsourcemap. Now I try upgrade  virtualenv before install sentry via pip.

\# pip install --upgrade pip
\# pip install --upgrade virtualenv

\# mkdir -p /sentry/sentry-venv
\# virtualenv /sentry/sentry-venv/
\# source /sentry/sentry-venv/bin/activate
\# pip install -U sentry

And Sentry setup successed. 

Thank for you Help! Maybe this commads helping everyone too (in google do not solved this problem).

**Comment by mattrobenolt** [comment]
It’s worth noting that by doing what you just did, you also updated to a newer version of Sentry which now doesn’t use libsourcemap.
