### ISSUE TITLE
pip install libsourcemap failed missing Cargo.toml

### ISSUE THREAD

**Issue by ayeowch** [getsentry/libsourcemap#2]
On Debian 8 (Jessie), Python 2.7.9,  Rust 1.12.1, I get the error below when running `pip install libsourcemap`.

Cargo.toml appears to be missing from https://pypi.python.org/packages/31/ea/f2a8440feae0d5a4c9487466e6c4e157870fa52ebc73ba224dea6c4d000d/libsourcemap-0.5.0.zip#md5=8d6ccc0f86229c10ba9a7c536033ff17. I am not sure if that should be included in the zip though. I believe it should be?

```
running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/highlevel.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/__init__.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/exceptions.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/_sourcemapnative.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/_compat.py -> build/lib.linux-x86_64-2.7/libsourcemap

error: could not find `Cargo.toml` in `/tmp/pip-build-8YhcNY/libsourcemap` or any parent directory
```

**Comment by mattrobenolt** [comment]
Are you explicitly trying to install from source? We distribute wheels which you should use instead. If you have pip 8.1, you'd get the wheel and not need to compile from source.

**Comment by ayeowch** [comment]
I was just running `pip install libsourcemap` in my virtualenv with pip 1.5.6. Looks like it should just work with pip 8.1.

**Comment by ayeowch** [comment]
@mattrobenolt Yup, using pip 8.1 works without issue. Thanks!
