### ISSUE TITLE
Error installing in MacOS X 10.12 as dependency of sentry

### ISSUE THREAD

**Issue by nt3rp** [getsentry/libsourcemap#3]
When I run this command...

```
MACOSX_DEPLOYMENT_TARGET="10.12" python setup.py develop
```

...in a virtual environment, I get the following error:

```
Installed /private/var/folders/2d/br7gpgdn7pd454jt4_3rp96m0000gp/T/easy_install-fkJy1m/libsourcemap-0.5.0/.eggs/pycparser-2.17-py2.7.egg
error: could not find `Cargo.toml` in `/private/var/folders/2d/br7gpgdn7pd454jt4_3rp96m0000gp/T/easy_install-fkJy1m/libsourcemap-0.5.0` or any parent directory
error: Setup script exited with 101
```

**Comment by mattrobenolt** [comment]
Is there a reason you're trying to install this from source? If you use a modern version of `pip`, it'll get installed already compiled and not needed.

**Comment by nt3rp** [comment]
Sorry, I didn't do a good job of explaining.

What I meant was, when I try to build [`sentry`](https://github.com/getsentry/sentry), I get the above error when it gets to the step for installing `libsourcemap`. If I try to install `libsourcemap` locally though (via `pip install .`) it works fine.

It would seem like its a problem with the compilation of `libsourcemap` rather than `sentry`, so I filed the bug here.

**Comment by mattrobenolt** [comment]
Yeah, so just upgrade your `pip` and you won't have to compile. This isn't really a problem with either project, but simply that you don't have the pre-requisites needed to be able to compile from source, which would be `rust` among other things, but you don't need to compile from source unless you're attempting to actually develop against master intentionally.
