### ISSUE TITLE
Error while installing with pip in debian jessie

### ISSUE THREAD

**Issue by badr-badri** [getsentry/libsourcemap#4]
Hello,
I get this error when I try to install libsourcemap with pip in Debian :

Installing collected packages: libsourcemap, cffi, pycparser
  Running setup.py install for libsourcemap
    error: [Errno 2] No such file or directory
    Complete output from command /root/sentry_1/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-SVsIt2/libsourcemap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tGDVJ6-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/sentry_1/include/site/python2.7:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/__init__.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/_compat.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/_sourcemapnative.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/exceptions.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/highlevel.py -> build/lib.linux-x86_64-2.7/libsourcemap

error: [Errno 2] No such file or directory

Cleaning up...
Command /root/sentry_1/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-SVsIt2/libsourcemap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tGDVJ6-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/sentry_1/include/site/python2.7 failed with error code 1 in /tmp/pip-build-SVsIt2/libsourcemap
Storing debug log for failure in /root/.pip/pip.log

This is the information found in pip.log:

Exception information:
Traceback (most recent call last):
  File "/root/sentry_1/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/root/sentry_1/local/lib/python2.7/site-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/root/sentry_1/local/lib/python2.7/site-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/root/sentry_1/local/lib/python2.7/site-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/root/sentry_1/local/lib/python2.7/site-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /root/sentry_1/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-SVsIt2/libsourcemap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tGDVJ6-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/sentry_1/include/site/python2.7 failed with error code 1 in /tmp/pip-build-SVsIt2/libsourcemap

**Comment by mattrobenolt** [comment]
You need a modern `pip`. `pip>=8.1` to be exact.
