### ISSUE TITLE
error: could not find `Cargo.toml` in `libsourcemap-0.5.0` or any parent directory

### ISSUE THREAD

**Issue by leoleovich** [getsentry/libsourcemap#5]
Hello!
I've seen you already have an issue https://github.com/getsentry/libsourcemap/issues/2, which describes my problem, but
I really need to build it from source (no pip installation). I am building Debian package and this error is preventing from doing it.
As a solution, I copied `Cargo.toml` from master branch of your project and located it in project directory.
Basically this is the command I am executing to build debian:
```
package='libsourcemap-0.5.0' 
py2dsc -m 'Oleg <leoleovich@domain.com>' ./${package}.zip
cd deb_dist/${package}
DEB_BUILD_OPTIONS=nocheck debuild -i -us -uc -b
```

It fails on the last step, because it runs
```
python setup.py build
```

Please put this file in there :)

**Comment by leoleovich** [comment]
I have all kinds of error without this file. 
For example it got path completely fucked up
```
 Downloading fs2 v0.2.5
   Compiling libsourcemap v0.5.0 (file:///root/sentry)
error: couldn't read "/root/sentry/src/libsourcemap.rs": No such file or directory (os error 2)
```

And after I added file
```
   Compiling libsourcemap v0.5.0 (file:///root/sentry/deb_dist/libsourcemap-0.5.0)
    Finished release [optimized] target(s) in 306.56 secs
``

**Comment by mitsuhiko** [comment]
I will make a release with the missing file in the manifest.

**Comment by Bolik** [comment]
+1

**Comment by mitsuhiko** [comment]
Forgot to close this issue.
