### ISSUE TITLE
Can install with pure-python on arm7, fails on libsourcemap

### ISSUE THREAD

**Issue by mt3o** [getsentry/libsourcemap#9]
I  have problems installing Sentry on my Raspberry PI. Is this even possible? Distro is latest Raspbian, almost all components are installed fine, except libsourcemap.

Can I do anything to make this up and running?

Below is install log:

(sentry) root@se-search-raspi:/var/www/sentry# pip install -U sentry
Collecting sentry
  Using cached sentry-8.14.1-py27-none-any.whl
Requirement already up-to-date: pytest-html<1.10.0,>=1.9.0 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: statsd<3.2.0,>=3.1.0 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: python-dateutil<3.0.0,>=2.0.0 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: ipaddress<1.1.0,>=1.0.16 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: requests[security]<2.13.0,>=2.9.1 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: lxml>=3.4.1 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: mmh3<2.4,>=2.3.1 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: setproctitle<1.2.0,>=1.1.7 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: django-picklefield<0.4.0,>=0.3.0 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: pytest<2.7.0,>=2.6.4 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: django-templatetag-sugar>=0.1.0 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: structlog==16.1.0 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: six<1.11.0,>=1.10.0 in ./lib/python2.7/site-packages (from sentry)
Requirement already up-to-date: email-reply-parser<0.3.0,>=0.2.0 in ./lib/python2.7/site-packages (from sentry)

(...)

Collecting setuptools>=11.3 (from cryptography>=1.3.4; extra == "security"->requests[security]<2.13.0,>=2.9.1->sentry)
  Downloading setuptools-34.3.3-py2.py3-none-any.whl (389kB)
    100% |████████████████████████████████| 399kB 10kB/s
Requirement already up-to-date: packaging in ./lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]<2.13.0,>=2.9.1->sentry)
Requirement already up-to-date: asn1crypto>=0.21.0 in ./lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]<2.13.0,>=2.9.1->sentry)
Requirement already up-to-date: pycparser in ./lib/python2.7/site-packages (from cffi>=1.6.0->libsourcemap<0.6.0,>=0.5.0->sentry)
Collecting docutils>=0.10 (from botocore<1.6.0,>=1.5.0->boto3<1.5,>=1.4.1->sentry)
  Using cached docutils-0.13.1-py2-none-any.whl
Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" (from s3transfer<0.2.0,>=0.1.10->boto3<1.5,>=1.4.1->sentry)
  Using cached futures-3.0.5-py2-none-any.whl
Requirement already up-to-date: appdirs>=1.4.0 in ./lib/python2.7/site-packages (from setuptools>=11.3->cryptography>=1.3.4; extra == "security"->requests[security]<2.13.0,>=2.9.1->sentry)
Requirement already up-to-date: pyparsing in ./lib/python2.7/site-packages (from packaging->cryptography>=1.3.4; extra == "security"->requests[security]<2.13.0,>=2.9.1->sentry)
Building wheels for collected packages: libsourcemap
  Running setup.py bdist_wheel for libsourcemap ... error
  Complete output from command /var/www/sentry/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4x_KPz/libsourcemap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpoiOcBipip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/libsourcemap
  copying libsourcemap/highlevel.py -> build/lib.linux-armv7l-2.7/libsourcemap
  copying libsourcemap/__init__.py -> build/lib.linux-armv7l-2.7/libsourcemap
  copying libsourcemap/exceptions.py -> build/lib.linux-armv7l-2.7/libsourcemap
  copying libsourcemap/_sourcemapnative.py -> build/lib.linux-armv7l-2.7/libsourcemap
  copying libsourcemap/_compat.py -> build/lib.linux-armv7l-2.7/libsourcemap
  error: [Errno 2] No such file or directory

  ----------------------------------------
  Failed building wheel for libsourcemap
  Running setup.py clean for libsourcemap
Failed to build libsourcemap
Installing collected packages: libsourcemap, percy, httplib2, oauth2, python-utils, progressbar2, ua-parser, Django, django-bitfield, symsynd, cssutils, cssselect, toronado, pytest-django, selenium, contextlib2, raven, redis, rb, python-u2flib-server, click, django-sudo, uwsgi, jmespath, docutils, botocore, futures, s3transfer, boto3, djangorestframework, sqlparse, django-debug-toolbar, mock, django-jsonfield, python-openid, simplejson, South, urllib3, exam, amqp, anyjson, kombu, Pillow, psycopg2, petname, PyYAML, hiredis, qrcode, django-crispy-forms, billiard, pytz, celery, python-memcached, honcho, sentry, setuptools
  Running setup.py install for libsourcemap ... error
    Complete output from command /var/www/sentry/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4x_KPz/libsourcemap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5AyIFJ-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/sentry/include/site/python2.7/libsourcemap:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/libsourcemap
    copying libsourcemap/highlevel.py -> build/lib.linux-armv7l-2.7/libsourcemap
    copying libsourcemap/__init__.py -> build/lib.linux-armv7l-2.7/libsourcemap
    copying libsourcemap/exceptions.py -> build/lib.linux-armv7l-2.7/libsourcemap
    copying libsourcemap/_sourcemapnative.py -> build/lib.linux-armv7l-2.7/libsourcemap
    copying libsourcemap/_compat.py -> build/lib.linux-armv7l-2.7/libsourcemap
    error: [Errno 2] No such file or directory

    ----------------------------------------
Command "/var/www/sentry/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4x_KPz/libsourcemap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5AyIFJ-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/sentry/include/site/python2.7/libsourcemap" failed with error code 1 in /tmp/pip-build-4x_KPz/libsourcemap/

root@se-search-raspi:/var/www/sentry# cat /proc/cpuinfo 
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

**Comment by mitsuhiko** [comment]
Installation on armv7 is unlikely to succeed. You would have to somehow crosscompile llvm for it.

**Comment by mt3o** [comment]
@mitsuhiko You mean I should have working llvm on arm first? I guess it's already done:
https://packages.debian.org/jessie/llvm

Since the libsourcemap is last dependency I struggle with, do you mind if we continue to talk here? :-) 
Until I give up or succeed with running Sentry on raspberry pi.

**Comment by mitsuhiko** [comment]
@mt3o that was in the context of sentry actually. libsourcemap in itself does not need it. libsourcemap might be good with just getting rust going but I'm pretty sure that there are plenty of things in sentry that do not support armv7.

We have no plans outselves to run on arm but I think there will be a dozen if not more problems with making it work there.
